#!/bin/sh

if [ -z "$1" ]; then
	GIT_VERSION="$(git --version)"

	cat <<EOF
Git Shell (${GIT_VERSION})
Run 'help' for help, or 'exit' to leave.

Available commands:
-------------------------------------------------------------
EOF

	cd "$(dirname "$0")" || exit 1

	for cmd in *; do
		case "$cmd" in
		help) ;;
		*) [ -f "$cmd" ] && [ -x "$cmd" ] && echo "$cmd" ;;
		esac
	done
else
	COMMAND="$1"

	case $COMMAND in
	git-init)
		echo "Initialize git repository."
		printf '\n'
		echo "Usage : git-init NAME OWNER [DESC] [SECTION]"
		;;
	git-config)
		echo "Modify git config."
		echo "If repository name is not given, modify global config."
		printf '\n'
		echo "Usage : git-config [NAME]"
		;;
	ls)
		echo "List repositories."
		printf '\n'
		echo "Usage : ls"
		;;
	*)
		echo "Not available command."
		;;
	esac
fi

printf '\n'
